### PR TITLE
Support json/jsx/tsx

### LINKED ISSUE #14: Add support for json files
Currently renaming a json file to .js basically adds this support so it should be easy to fix

### PR DESCRIPTION
**Pull request by somarlyonks**
fixes #14

### CODE REVIEW

**Comment by technoabyss** [comment]
Please merge this! @jamesohortle

**Comment by jamesohortle** [comment]
@somarlyonks @technoabyss 

Hello all,

Thanks for the pull request. It looks great. Before merging, my only requirement is to have files in `src/test` folder. You can use the same code points used for testing the other test files. Please add these test files to the merge request and I will merge.

Apologies for the delay in replying.

**Comment by somarlyonks** [comment]
@jamesohortle added

**Comment by jamesohortle** [comment]
@somarlyonks 
Hi, I'm back in lockdown again so I finally have some time to look at this. I'm trying to debug locally and it looks like the tests for HTML entities aren't successful for .tsx and .jsx files. When I hover over, for example, `&ecaron;` I don't see a panel. Is this expected behaviour? I'm not a react developer, so I'm not sure if the tests are failing or if this test is testing a behaviour that shouldn't exist.

**Comment by jamesohortle** [comment]
I'm going to go ahead and merge since it seems like there is demand for this PR. @somarlyonks if you realise that the tests are _**failing**_ then please submit a new PR.

**Pull request merged**
